version: "3.7"

services:

  database:  # The service name has to be "database", if we change it the app cannot establish a connection.
    image: mysql:5.7  
    container_name: database 
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: cagatay
      MYSQL_PASSWORD: P@ssword
    networks:
      - clarusnet

  myapp:
    image: bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
