---
# tasks file for docker
- name: update packeges
  yum:
    name: "*"  #all packages
    state: latest

- name: uninstall old versions  # https://docs.docker.com/engine/install/centos/
  yum: 
    name: "{{ item }}"
    state: removed
  loop:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: install yum-utils
  yum: 
    name: yum-utils
    state: latest

- name: Add Docker repo  
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  package:  
    name: docker-ce
    state: latest

- name: install pip   # https://docs.ansible.com/ansible/2.9/modules/docker_image_module.html
  package: 
    name: python3-pip
    state: latest

- name: install docker-sdk  # https://docs.ansible.com/ansible/2.9/modules/docker_image_module.html
  pip: 
    name: docker

- name: add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: start docker service
  systemd:
    name: docker
    enabled: yes
    state: started